spring.application.name=gestion-socios
# Configuración base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:aspacacorbd;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Forzar la activación de la consola web de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Mostrar SQL en la consola de comandos
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update